// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TetsProject.Migrations
{
    [DbContext(typeof(DenemeContext))]
    [Migration("20230504082455_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("xSequence");

            modelBuilder.Entity("x", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [xSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Xaçıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("x");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("q", b =>
                {
                    b.HasBaseType("x");

                    b.Property<string>("Qaçıkalam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("q");
                });

            modelBuilder.Entity("y", b =>
                {
                    b.HasBaseType("x");

                    b.Property<string>("Yaçıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("y");
                });

            modelBuilder.Entity("z", b =>
                {
                    b.HasBaseType("y");

                    b.Property<string>("Zaçıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("z");
                });
#pragma warning restore 612, 618
        }
    }
}
